kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.24.3
  labels:
    cri: containerd

- role: worker
  image: kindest/node:v1.24.3
  labels:
    cri: containerd
  extraMounts:
  - hostPath: e2e/kind/.work/log
    containerPath: /host/log

- role: worker
  image: kindest/node-crio:v1.24.3
  labels:
    cri: cri-o
  extraMounts:
  - hostPath: e2e/kind/.work/image
    containerPath: /host/image
  - hostPath: e2e/kind/.work/log
    containerPath: /host/log
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      criSocket: unix:///run/crio/crio.sock
      kubeletExtraArgs:
        cgroup-driver: cgroupfs
