apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: strict-supplementalgroups-system

resources:
- ds.yaml
- namespace.yaml
- rbac.yaml
- runtime.yaml

configMapGenerator:
- name: config-containerd
  files:
  - config.toml=config/config-containerd.toml
- name: config-crio
  files:
  - config.toml=config/config-crio.toml
  - patch.toml=config/crio-patch.toml
