name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  goreleaser:
    name: Release Binaries And Docker Images
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17
        id: go
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Devtools
        run: make ci-setup
      - name: Get dependencies
        run: go mod download

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
